<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-74PA3RG" ignored="0" name="functional testing" tests="2" failures="2" timestamp="2020-09-01T20:51:58 IST" time="50.739" errors="0">
  <testcase name="doo" time="0.014" classname="Pack1.Base">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Pack1.Base.doo(Base.java:250)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- doo -->
  <testcase name="doo" time="0.04" classname="Pack1.Base">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at pack2.Failureoperation.onTestFailure(Failureoperation.java:25)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- doo -->
</testsuite> <!-- functional testing -->
